name: Django Test

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Preparing settings
        run: |
          docker compose up --build -d
      - name: Restarting Django service
        run: docker restart time-tracker-be
      - name: Setup test prerequisites
        run: |
          docker exec -iu root time-tracker-be mkdir /home/django/var
          docker exec -iu root time-tracker-bechown django:django -R /home/django/var
          docker exec -iu root time-tracker-be chmod 755 -R /home/django/var
      - name: Prepare migrations and static data
        run: |
          docker exec -i time-tracker-be python manage.py migrate
          docker exec -i time-tracker-be python manage.py collectstatic --noinput
      - name: Running Test
        run: |
          docker exec -i time-tracker-be python manage.py test --parallel
